


services:
  bot:
    build: .
    image: chat-bot:alpine
    container_name: chat_con
    restart: always
    command: "sh -c 'python3 main.py'"
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: chat_pg
    restart: always
    environment:
      POSTGRES_PASSWORD : 1
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql
  web:
    build: .
    image: chat-web:alpine
    container_name: chat_web
    restart: always
    command: "uvicorn web.app:app --host web --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  pg_data: